#!/bin/bash

set -o errexit

export LC_ALL=en_US.utf8
export LANGUAGE=en_US.utf8
export LANG=en_US.utf8

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

echo "* Get latest updates"
export DEBIAN_FRONTEND=noninteractive
apt-get -y update
yes no | apt-get -y upgrade
apt-get -y dist-upgrade

echo "* Setup nginx"
mv /usr/local/var/tmp/nginx.conf /etc/nginx/nginx.conf
ln -nfs /etc/nginx/sites-available/mailtrain /etc/nginx/sites-enabled/mailtrain
mkdir -p /etc/nginx/ssl
chmod 0500 /etc/nginx/ssl
/usr/local/bin/ssl-selfsigned.sh -d /etc/nginx/ssl -f mailtrain

echo "* Setup mongodb"
curl -fsSL https://www.mongodb.org/static/pgp/server-4.2.asc | apt-key add - || true
echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.2 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-4.2.list

apt-get -y update
apt-get -y install mongodb-org

echo "* Setup node"
/usr/local/var/tmp/setup_14.x
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 9DA31620334BD75D9DCB49F368818C72E52529D4
apt-get -y update
apt-get -y install nodejs

echo "* Setup mailtrain"
mkdir -p /var/www/mailtrain
addgroup mailtrain
adduser --disabled-password --system --quiet --home /var/www/mailtrain --shell /bin/bash mailtrain
adduser mailtrain mailtrain
(
  cd /var/www/mailtrain
  git clone https://github.com/Mailtrain-org/mailtrain.git .
  git checkout v2
  chown -R mailtrain:mailtrain .
)

echo "* Extend history"
cat >> /root/.bash_history << EOF
systemctl restart mongod
systemctl status mongod
systemctl edit --full mailtrain
systemctl daemon-reload
systemctl restart mailtrain
systemctl status mailtrain
EOF

echo "* Ensure bootstrap will run next time"
rm -rf /var/lib/bootstrap

echo "* Cleaning up."
apt-get -y purge git make gcc g++ build-essential
rm /var/log/syslog || true
touch /var/log/syslog || true
rm /root/customize
history -c
