#!/bin/bash

set -o errexit

NODE_JS_VERSION="14.21.3"

export LC_ALL=en_US.utf8
export LANGUAGE=en_US.utf8
export LANG=en_US.utf8

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

echo "* Get latest updates"
export DEBIAN_FRONTEND=noninteractive
apt-get -y update
yes no | apt-get -y upgrade
apt-get -y dist-upgrade

echo "* Setup nginx"
mv /usr/local/var/tmp/nginx.conf /etc/nginx/nginx.conf
ln -nfs /etc/nginx/sites-available/mailtrain /etc/nginx/sites-enabled/mailtrain
mkdir -p /etc/nginx/ssl
chmod 0500 /etc/nginx/ssl
/usr/local/bin/ssl-selfsigned.sh -d /etc/nginx/ssl -f mailtrain

echo "* Setup mongodb (only used my onemta)"
if [[ $(grep -c "18.04" /etc/lsb-release) -ge 1 ]]; then
  echo "*** Install mongodb on 18.04"
  curl -fsSL https://www.mongodb.org/static/pgp/server-4.2.asc | apt-key add - || true
  echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.2 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-4.2.list
elif [[ $(grep -c "20.04" /etc/lsb-release) -ge 1 ]]; then
  echo "*** Install mongodb on 20.04"
  curl -fsSL https://www.mongodb.org/static/pgp/server-4.4.asc | apt-key add - || true
  echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-4.4.list
elif [[ $(grep -c "22.04" /etc/lsb-release) -ge 1 ]]; then
  echo "*** Install mongodb on 22.04"
  curl -fsSL https://www.mongodb.org/static/pgp/server-5.0.asc | apt-key add - || true
  echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/5.0 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-5.0.list
else
  echo "*** ERROR: wrong ubuntu release, skip mongodb installation"
fi

apt-get -y update
apt-get -y install mongodb-org
sed -i "s/^#  engine:/  engine: wiredTiger/" /etc/mongod.conf

echo "* Setup node"
apt-get -y install npm
npm install -g inherits n
/usr/local/bin/n $NODE_JS_VERSION
# npm install npm@latest -g

echo "* Setup mailtrain"
mkdir -p /var/www/mailtrain
addgroup mailtrain
adduser --disabled-password --system --quiet --home /var/www/mailtrain --shell /bin/bash mailtrain
adduser mailtrain mailtrain
(
  cd /var/www/mailtrain
  git clone https://github.com/Mailtrain-org/mailtrain.git .
  git checkout v2
  chown -R mailtrain:mailtrain .
)

echo "* Extend history"
cat >> /root/.bash_history << EOF
vim /var/www/mailtrain/server/services/workers/reports/config/production.yaml
vim /var/www/mailtrain/server/config/production.yaml
systemctl edit --full mailtrain
systemctl daemon-reload
systemctl restart mailtrain
systemctl status mailtrain
EOF

echo "* Ensure bootstrap will run next time"
rm -rf /var/lib/bootstrap

echo "* Cleaning up."
rm /var/log/syslog || true
touch /var/log/syslog || true
rm /root/customize
history -c
